switch to stack builder

diff --git a/.github/workflows/build_branch.yml b/.github/workflows/build_branch.yml
--- a/.github/workflows/build_branch.yml
+++ b/.github/workflows/build_branch.yml
@@ -4,25 +4,15 @@ on: pull_request
 jobs:
   build:
     # if: github.repository == 'jocosocial/swiftarr'
-    runs-on: macos-15
+    runs-on: ubuntu-22.04
     steps:
-    - name: Get swift version
-      run: swift --version # Swift 6.0
-    # https://github.com/swift-actions/setup-swift/issues/683
-    # - name: Install Swift
-    #   uses: swift-actions/setup-swift@v2
-    #   with:
-    #     swift-version: "6.0"
-    - name: Install GD Dependency
-      run: brew install gd
     - name: Checkout Swiftarr
       uses: actions/checkout@v2
-    - name: Setup Postgres
-      run: .github/workflows/setup-runner-postgres.sh
-    - name: Install Redis
-      run: .github/workflows/setup-runner-redis.sh
-    - name: Run Build
-      run: swift build -c release
-    # Deploy
-    - name: Perform Database Migrations
-      run: swift run swiftarr migrate --yes
+    - name: Build Stack
+      run: scripts/stack.sh -e github build
+    - name: Run Stack
+      run: scripts/stack.sh -e github up -d
+    - name: Wait
+      run: sleep 15
+    - name: Check for Health
+      run: curl -f -s -o /dev/null http://localhost:8069/api/v3/client/health || { echo "Endpoint test failed"; exit 1; }
